id: P000816
initial_creation_type: ebook
created_at: 5/04/2021
last_modified_at: 24/11/2021
source_metadata:
  title: test
  subtitle: test
  authors:
  - test
  collection: test
  publisher: test
  id: sku-01
  cover: tmpl0pbn2rk.jpg
  credit: tmpjo34sl13.jpg
